name: Build and Deploy to EC2

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]
    
  workflow_dispatch:


jobs:
  build-project:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      # 체크아웃
      - name: checkout release
        uses: actions/checkout@v4

      # JDK 17 세팅
      - name: set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # gradlew 권한 설정
      - name: Make gradlew executable
        run: chmod +x ./gradlew
        
      # Build Gradle
      - name: Build with Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5
        with:
          arguments: clean build -x test
